### ISSUE TITLE
Tabs opened from pinned tabs get not grouped

### ISSUE THREAD

**Issue by GM-Alex** [FaisalBinAhmed/tabius#4]
Hi,

tabs which are opened from a pinned tab are not grouped if there is more than one. So for example if I have a pinned tab for google mail, my expectation is that the first mail I open in a new tab will be in no group, but if I open a second mail it should be grouped.

**Comment by FaisalBinAhmed** [comment]
Hi @GM-Alex, sorry for late reply, I just noticed this.

This is by design. Pinned tabs cannot be grouped, if they are grouped then they get unpinned by Chrome automatically.

Whichever tabs you open from a pinned tab will not get grouped, but if you open a new tab from that 2nd tab, they will be grouped together.

**Comment by GM-Alex** [comment]
Okay I see. I found an other extension which does like requested in this is issue. But thanks for your reply.
